version: '3.8'

# AWS生产环境配置
# 使用: docker-compose -f docker-compose.yml -f docker-compose.aws.yml up
services:
  # 应用服务
  fraud-detection-service:
    environment:
      # 覆盖默认环境变量
      - SPRING_PROFILES_ACTIVE=prod
      # AWS 区域
      - AWS_REGION=${AWS_REGION:-us-east-1}
      
      # 启用SQS，禁用Kafka
      - FRAUD_DETECTION_KAFKA_ENABLED=false
      - FRAUD_DETECTION_AWS_SQS_ENABLED=true
      
      # AWS SQS配置
      - FRAUD_DETECTION_AWS_SQS_TRANSACTION_QUEUE=${AWS_SQS_TRANSACTION_QUEUE}
      - FRAUD_DETECTION_AWS_SQS_RESULT_QUEUE=${AWS_SQS_RESULT_QUEUE}
      - FRAUD_DETECTION_AWS_SQS_ALERT_QUEUE=${AWS_SQS_ALERT_QUEUE}
      
      # AWS Secrets Manager/Parameter Store配置
      - SPRING_CLOUD_AWS_SECRETSMANAGER_ENABLED=true
      - SPRING_CLOUD_AWS_PARAMETERSTORE_ENABLED=true
    volumes:
      # 挂载AWS证书和密钥
      - ${AWS_CREDENTIALS_PATH:-~/.aws}:/root/.aws:ro
    # 添加AWS服务的健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/check"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "${AWS_REGION:-us-east-1}"
        awslogs-group: "fraud-detection-service"
        awslogs-stream: "fraud-detection-service-${ENVIRONMENT:-prod}" 