apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection-service
  labels:
    app: fraud-detection-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fraud-detection-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fraud-detection-service
    spec:
      containers:
      - name: fraud-detection-service
        image: ${DOCKER_REGISTRY}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 1Gi
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "test"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
        - name: SERVER_UNDERTOW_WORKER_THREADS
          value: "64"
        - name: SERVER_UNDERTOW_IO_THREADS
          value: "16"
        - name: aliyun_logs_logstore-fraud-detect
          value: /app/logs/*.log
        livenessProbe:
          httpGet:
            path: /api/check
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/check
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-service
  labels:
    app: fraud-detection-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: fraud-detection-service
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fraud-detection-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fraud-detection-service
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 